### ISSUE TITLE
Route of bus service 857 is slightly incorrect

### ISSUE THREAD

**Issue by btzy** [cheeaun/busrouter-sg#13]
Hi,
The route for service 857 (towards Suntec City/Marina Centre) is shown on your map to make a small loop through Toa Payoh, but in reality it seems to head straight to PIE (Jalan Toa Payoh) from the CTE...  this might be another bad route from mytransport.sg?

**Comment by cheeaun** [comment]
@btzy is this still incorrect? I suppose this happened during the F1 race when bus routes start to change.

**Comment by btzy** [comment]
It's still incorrect... It's the section that is closest to toa payoh.

**Comment by cheeaun** [comment]
@btzy is it possible for you to take a screenshot of where the error is?

**Comment by btzy** [comment]
Here it is:
imageshack.com/a/img905/2166/8MNXNU.png

It's the loop through Toa Payoh on your map... In reality it doesn't go through Toa Payoh.

**Comment by cheeaun** [comment]
I think this is probably an error from mytransport.sg 😓 You can try to see the route from http://www.mytransport.sg/content/mytransport/map.html too

**Comment by btzy** [comment]
It seems to be correct at mytransport.sg...
Here is my screenshot: [[http://imagizer.imageshack.us/a/img908/8696/C8baet.png]]

**Comment by cheeaun** [comment]
@btzy oh! gotcha, now I get your point :smile: Will look into this and fix it :+1:

**Comment by btzy** [comment]
Great job though! It's very easy to use and has a good mobile layout too

**Comment by cheeaun** [comment]
<img width="538" alt="screenshot 2019-01-15 at 1 26 43 pm" src="https://user-images.githubusercontent.com/2296/51160590-9d6a6700-18c9-11e9-89c7-12c7b550d15d.png">

Seems fixed now. Closing issue.
