### ISSUE TITLE
Display two bus routes at same time? (New features)

### ISSUE THREAD

**Issue by tianqig** [cheeaun/busrouter-sg#14]
It would be

**Comment by cheeaun** [comment]
Possibly duplicated of #1

**Comment by yEngineer7** [comment]
I believe this is already in place with the multiple route selection feature? (e.g. https://busrouter.sg/#/services/117~169~883)

Many thanks for that!

**Comment by cheeaun** [comment]
@yEngineer7 you're right. Closing this and #1 too 🥳 🎉
