### ISSUE TITLE
Route Amendment of SMRT 951E, Amendments due to Joo Koon Interchange Launch and New Bus Services 47, 117 & 118 Not Reflected

### ISSUE THREAD

**Issue by lawrencel1m** [cheeaun/busrouter-sg#15]
Hi, I have been an avid user of SBRE since I found out about it around half a year ago. However, I have noticed that some of the information has been outdated.

Firstly, the route of SMRT service 951E has been slightly tweaked in Woodlands, with the service skipping parts of Ave 4 and the whole of Ave 1, plying via Ave 5 and a longer section of Ave 12 instead, since 12 October 2015. Diagrams and details can be found here: http://www.smrt.com.sg/Portals/0/PDFs/Press%20Release/2015/SMRT%20Svc%20951E%20Route%20Amendment%20Poster%20final.pdf

Secondly, the routes of numerous SBS services serving Boon Lay and Joo Koon have been amended, while some routes have been added, in conjunction with the launch of Joo Koon Interchange. Due to the long list of route amendments, new bus routes and my lack of knowledge about the bus services in the area, I am only able to provide you with an external link with all the details here: https://publictransportsg.wordpress.com/2015/10/21/joo-koon-bus-interchange-launch-guide/

Lastly, there are 3 new SBS services which were just launched yesterday on 20 December 2015. The services are 47, 117 and 118, plying between Changi Business Park Terminal-Amber Road (Loop), Sembawang-Punggol and Changi Business Park-Punggol, respectively. More information can be found here: https://www.sbstransit.com.sg/download/svcs_47_117_118_979.pdf . In addition, there would be a new SMRT service 979 and a route amendment to service 983, as well as numerous minute amendments to buses serving around the new Bukit Panjang MRT in the upcoming week taking place on 27 December 2015. All information is at this link: https://publictransportsg.wordpress.com/2015/12/08/dtl2-bukit-panjang-bus-service-enhancements/ .

Thank you for your attention :)

**Comment by cheeaun** [comment]
Data is updated via 92d671ad3be0f2bb203b9287fe4062b97061b92d. So far I can just pinpoint on specific bus services:

- [ ] 951E - it's there but data still points to old bus stops :cry: 
- [x] 47
- [x] 117
- [x] 118
- [x] 979
- [x] 983

**Comment by cheeaun** [comment]
`951E` data is finally updated in 4812edc6bfbb16d4f505b6d769f35cb63293e291
