### ISSUE TITLE
Errors found from routes 853, 853C, and 81

### ISSUE THREAD

**Issue by hyjlw** [cheeaun/busrouter-sg#17]
Dear Sir/Mdm,
We found wrong GPS points from routes 853 and 853C, and route 81 should be a single direction route while you provided us with a dual-directional route.

We would appreciate that you let us know upon completion of the updates.

**Comment by cheeaun** [comment]
Hi, sorry for the late response here.

For routes 853 and 853C, may I know which points are wrong? Would be great if you could pinpoint them for me :smile: 

As for route 81, I've fixed it and it's now a single direction route.

Thanks!

**Comment by cheeaun** [comment]
Closing due to lack of response.

- [853](https://busrouter.sg/#/services/853) looks okay for me now.
- 853C seems non-existent now
- [81](https://busrouter.sg/#/services/81) is single-route now.
