### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by litena** [cheeaun/busrouter-sg#18]
Perhaps you would consider adding a license? Forgive me if I missed it.

**Comment by cheeaun** [comment]
@litena hmm you mean license for the app or the data?

**Comment by litena** [comment]
I meant the app. I understand that the data is from LTA.

**Comment by thehawk** [comment]
Hello @cheeaun, good app I was about to start somrthing lika this and I wonder about the liecence?!!!!
