### ISSUE TITLE
Just curious about list of bus stops and bus numbers

### ISSUE THREAD

**Issue by 4tee** [cheeaun/busrouter-sg#20]
Hi.. one of great projects. Saw the railrouter and taxirouter too. Just curious.
How do you get the list of all bus stops and bus numbers. I checked out in LTA datamall, but it seems like it doesn't provide the whole list. Thanks.

**Comment by cheeaun** [comment]
Hi @4tee here you see a list of scripts I use to scrape the data from LTA's website https://github.com/cheeaun/busrouter-sg/tree/master/tasks

These are not the official LTA datamall APIs, unfortunately.

**Comment by 4tee** [comment]
Awesome. Thanks.
