### ISSUE TITLE
Failing to run grunt fetchBusServices task

### ISSUE THREAD

**Issue by rarkins** [cheeaun/busrouter-sg#22]
I download the repo and then attempt the instructions as per README.

```
$ grunt fetchBusServices
Running "fetchBusServices" task
Request to mytransport.sg
Request to transitlink.com.sg
Fatal error: Cannot read property 'toLowerCase' of null
```

Am I somehow doing something wrong, or has something about their website changed?

**Comment by cheeaun** [comment]
Closing this, now that I've rewritten all the scripts.
