### ISSUE TITLE
Fetching alternative services (e.g. CDS)

### ISSUE THREAD

**Issue by hongshaoyang** [cheeaun/busrouter-sg#23]
Hi,

Possible to add the City Direct Services (CDS) by fetching from alternative website? Unfortunately after much scouring the interwebz for a definitive list of CDSes I failed to find any (tsk, LTA) but here are a few links I could perhaps point you to:

* [LTA Press Release](https://www.lta.gov.sg/apps/news/page.aspx?c=2&id=3fa25052-7ccd-42e2-89ae-7301b25b0180#1)
* [landtransportguru](http://landtransportguru.net/tag/city-direct/) looks reliable and often updated. this looks like the best website around. 

thanks so much!

**Comment by yEngineer7** [comment]
Yup, seems that CDS have been updated.
