### ISSUE TITLE
Not loading Google Maps correctly

### ISSUE THREAD

**Issue by hongshaoyang** [cheeaun/busrouter-sg#26]
`This page can't load Google Maps correctly` error appears when loading on my Android Phone.
![image](https://user-images.githubusercontent.com/19281800/45467292-74866980-b751-11e8-86a6-7327563a1f4f.png)

**Comment by liakwee** [comment]
This is due to recent google map platform change http://mapsplatform.googleblog.com/2018/05/introducing-google-maps-platform.html

**Comment by cheeaun** [comment]
Hi I've recently set a limit on API calls for Google Maps. I set it quite low, so I have bumped it up a little higher so the maps should able to load now.

**Comment by cheeaun** [comment]
Closing this issue for now.

Over the next few days, I'll constantly tweak the limits to ensure a balance between usability and cost. But once the monthly cost for Google Maps API start to rise beyond my budget, I'll have to restrict them further.

**Comment by bnjmnt4n** [comment]
A possible suggestion - the page for bus arrivals at each specific bus stop seems like an unnecessary usage of Google Maps. The static background image of each stop does not have as much of a meaningful user impact as the fluid and navigable embedded map on the main site, especially on mobile where it might be too small to make out meaningful details.

Then again - I'm not too sure what is the biggest contributor of API calls, so please take this with a pinch of salt.
