### ISSUE TITLE
Service 173 has many excessive lines

### ISSUE THREAD

**Issue by btzy** [cheeaun/busrouter-sg#30]
It seems that service 173 has lots of excessive edges cluttering the route:

![image](https://user-images.githubusercontent.com/6948096/50884203-2ba3a080-1425-11e9-9f89-afa6cdca118e.png)

Other services around the area seem to be okay.

**Comment by cheeaun** [comment]
Haha yeah, data comes from Tower Transit SG site itself, which I've mentioned to them... https://twitter.com/cheeaun/status/1064133116078415872

If they still haven't fix it, I'll use a different data source soon.

**Comment by cheeaun** [comment]
Fixed in 4521cd88f634d0f3ca2051b74c69e8c6778a949a

<img width="461" alt="screenshot 2019-01-15 at 8 04 03 pm" src="https://user-images.githubusercontent.com/2296/51179536-c3f7c480-1900-11e9-9f57-873dc3179c57.png">
