### ISSUE TITLE
167e wrong route

### ISSUE THREAD

**Issue by lihweilihwei** [cheeaun/busrouter-sg#32]
The express segment of 167e is wrong. Between bus stop 56099 and 50069, 167e takes the SLE -> CTE to the Moulmein Rd exit. The same applies to the opposite direction (btwn 50061 to 56091).

The route displayed on mytransport.sg (https://www.mytransport.sg/content/mytransport/map.html) is wrong too, so I guess that's the source of error. 

Is it possible for me to directly edit the routes json in the '3' folder?

**Comment by cheeaun** [comment]
You're right. Also shown here on the poster https://landtransportguru.net/event/launch-of-new-express-bus-service-167e/

<img width="320" alt="screenshot 2019-02-17 at 4 16 01 pm" src="https://user-images.githubusercontent.com/2296/52910222-5a881e80-32cf-11e9-9c32-e105019e9e2b.png">

Usually I don't fix route errors especially when the data source is wrong. After all, the point of the route lines is to tell that stop A goes to stop B, with **no guarantees** of which road the bus might take. Some *other* apps simply draw straight lines in between 😅. Fixing and maintaining route lines also tend to be very tedious, so I would rather wait for the data source to be fixed instead.

Another (easier) way to fix this is perhaps report or send feedback to mytransport.sg 😃

**Comment by lihweilihwei** [comment]
Okay I'll send feedback to mytransport then. Thanks!

**Comment by lihweilihwei** [comment]
Route has been updated on MyTransport and on busrouter.sg
