### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by vote539** [cheeaun/busrouter-sg#4]
Thanks for making this!  It's better than anything I've been able to find elsewhere.

I'm having trouble with Cross-Origin Resource Sharing when launching the app [from github.io](http://cheeaun.github.io/busrouter-sg/).  It looks like the app is trying to AJAX to an S3 instance, but the CORS headers are not allowing the connection.  I temporarily fixed the issue for me by [disabling CORS in Firefox](http://stackoverflow.com/questions/17711924/disable-cross-domain-web-security-in-firefox), but of course this isn't something most people should be doing when visiting the site.  Can you look into enabling CORS in S3?  [This article](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) might help.

P.S. This was the top hit in Google for "singapore bus map".  Nice job.

**Comment by cheeaun** [comment]
I guess this is not happening anymore. Do open another issue if this happens again.
