### ISSUE TITLE
Missing Bus routes

### ISSUE THREAD

**Issue by hasanp87** [cheeaun/busrouter-sg#6]
Hi,
     Your json data for the bus routes and bus stops is very useful. There are a few missing bus routes in the data. Can you add the same ? 
I am attaching the service numbers of all the missing routes
route_id
103M-1
125X-1
128-0
170#-1
170#-2
177-2
179A-1
180-2
195A-1
1M-1
231-2
24-2
27-2
284M-1
2M-1
34-2
372-2
3M-1
409-1
4M-1
529-1
53-2
530-1
531-1
531-2
532-1
533-1
534-1
535-1
536-1
537-1
538-1
539-1
540-1
542-1
543-1
544-1
545-1
546-1
548-1
549-1
550-1
551-1
552-1
553-1
554-1
555-1
556-1
557-1
558-1
559-1
560-1
561-1
563-1
564-1
565-1
566-1
569-1
575-1
577-1
580-1
585-1
587-1
588-1
589-1
59-12
590-1
598-1
599-1
5M-1
60X-1
68-1
6M-1
761-1
7M-1
7N-1
85X-1
868E-1
8M-1
8N-1
Premium-1-1
Premium-1-2
Premium-10-1
Premium-11-1
Premium-12-1
Premium-2-1
Premium-3-1
Premium-3-2
Premium-4-1
Premium-4-2
Premium-5-1
Premium-521-1
Premium-522-1
Premium-523-1
Premium-524-1
Premium-525-1
Premium-526-1
Premium-528-1
Premium-529-1
Premium-530-1
Premium-531-1
Premium-531-2
Premium-532-1
Premium-533-1
Premium-534-1
Premium-535-1
Premium-536-1
Premium-537-1
Premium-538-1
Premium-539-1
Premium-540-1
Premium-541-1
Premium-541-2
Premium-542-1
Premium-543-1
Premium-544-1
Premium-545-1
Premium-546-1
Premium-547-1
Premium-547-2
Premium-548-1
Premium-549-1
Premium-550-1
Premium-551-1
Premium-552-1
Premium-553-1
Premium-554-1
Premium-555-1
Premium-556-1
Premium-557-1
Premium-558-1
Premium-559-1
Premium-560-1
Premium-561-1
Premium-562-1
Premium-562-2
Premium-563-1
Premium-564-1
Premium-565-1
Premium-566-1
Premium-567-1
Premium-567-2
Premium-568-1
Premium-569-1
Premium-570-1
Premium-571-1
Premium-571-2
Premium-572-1
Premium-572-2
Premium-573-1
Premium-573-2
Premium-574-1
Premium-574-2
Premium-575-1
Premium-576-1
Premium-577-1
Premium-578-1
Premium-579-1
Premium-580-1
Premium-581-1
Premium-582-1
Premium-585-1
Premium-587-1
Premium-588-1
Premium-592-1
Premium-593-1
Premium-6-1
Premium-7-1
Premium-8-1
Premium-9-1
RW88-1
SS1-1
SS2-1
SS3
SS3-1
SS4-1

**Comment by cheeaun** [comment]
Closing to lack of response and the possibility that the data listed is outdated now.
