### ISSUE TITLE
Roads seem to be missing?

### ISSUE THREAD

**Issue by yuuka-miya** [cheeaun/busrouter-sg#81]
Microsoft Edge 103.0.1264.49.

Map renders like that for me with roads missing.

![image](https://user-images.githubusercontent.com/1886269/178109025-49a89648-b546-4e1e-b0fa-0b105a46ccbc.png)

If it helps, I use uBlock Origin, but the issue persists even after turning uBO off.

**Comment by cheeaun** [comment]
Hi @yuuka-miya is this still happening now?

**Comment by cheeaun** [comment]
@yuuka-miya does this happen when you open it in incognito mode too?

**Comment by yuuka-miya** [comment]
Yep. Seeing this on Firefox as well.

Then again could just be my PC (Windows 11 Build 22622). The map renders properly on my phone.

I guess can be closed if you can't reproduce.

**Comment by cheeaun** [comment]
@yuuka-miya I upgraded the maps library, which I suspected the bug comes from there. Do you still see this bug? 🙏

**Comment by yuuka-miya** [comment]
Yep, resolved now. Thanks!
