### ISSUE TITLE
Backporting functionalities to the old version

### ISSUE THREAD

**Issue by yEngineer7** [cheeaun/busrouter-sg#84]
Hi, I currently have a need to work using a different browser (LibreWolf). It doesn't support the newest map version and redirects me to the older version (v1.busrouter.sg), which unfortunately doesn't have some functions such as multi-service display, display of service numbers on route lines, and the up-to-date routings.

May I ask if you could try, as a test, to backport (a) the up-to-date routings, (b) the multi-service display function (i.e. "services/2~3~4")? And if possible also (c) showing service numbers on route lines, and (d) showing bus stop codes and names on zoomed in?

Much thanks~

**Comment by cheeaun** [comment]
@yEngineer7 is it possible to enable "WebGL" on your LibreWolf? (Go to `Settings`, type "webgl" in the `Find in Settings` search field, tick on the "Enable WebGL" checkbox).

Sorry, I'm no longer maintaining the older version for many reasons 🙏
